/*
  # Insert Bars Data

  1. Data Import
    - Insert all bars from Asia's 50 Best Bars 2025 rankings
    - Include both 2024 and 2025 rankings where available
    - Cover ranks 1-100 with proper city and country data
*/

INSERT INTO bars (name, rank_2025, city, country) VALUES
('Bar Leone', 1, 'Hong Kong', 'Hong Kong'),
('Zest', 2, 'Seoul', 'South Korea'),
('Jigger & Pony', 3, 'Singapore', 'Singapore'),
('Coa', 4, 'Hong Kong', 'Hong Kong'),
('Bar Benfiddich', 5, 'Tokyo', 'Japan'),
('Nutmeg & Clove', 6, 'Singapore', 'Singapore'),
('BKK Social Club', 7, 'Bangkok', 'Thailand'),
('Penrose', 8, 'Kuala Lumpur', 'Malaysia'),
('Argo', 9, 'Hong Kong', 'Hong Kong'),
('The Aubrey', 10, 'Hong Kong', 'Hong Kong'),
('Virtù', 11, 'Tokyo', 'Japan'),
('The Cocktail Club', 12, 'Jakarta', 'Indonesia'),
('Vesper', 13, 'Bangkok', 'Thailand'),
('Hope & Sesame', 14, 'Guangzhou', 'China'),
('Tell Camellia', 15, 'Hong Kong', 'Hong Kong'),
('28 HongKong Street', 16, 'Singapore', 'Singapore'),
('Darkside', 17, 'Hong Kong', 'Hong Kong'),
('Bar Trench', 18, 'Tokyo', 'Japan'),
('The Savory Project', 19, 'Hong Kong', 'Hong Kong'),
('Bar Cham', 20, 'Seoul', 'South Korea'),
('Bar Us', 21, 'Bangkok', 'Thailand'),
('The St. Regis Bar (Macau)', 22, 'Macau', 'Macau'),
('Lamp Bar', 23, 'Nara', 'Japan'),
('Penicillin', 24, 'Hong Kong', 'Hong Kong'),
('Offtrack', 25, 'Singapore', 'Singapore'),
('Reka', 26, 'Kuala Lumpur', 'Malaysia'),
('Bar Mood', 27, 'Taipei', 'Taiwan'),
('Jing Bar', 28, 'Beijing', 'China'),
('Smoke & Bitters', 29, 'Himeji', 'Japan'),
('Vender', 30, 'Taichung', 'Taiwan'),
('Native', 31, 'Singapore', 'Singapore'),
('Sago House', 32, 'Singapore', 'Singapore'),
('Craftroom', 33, 'Osaka', 'Japan'),
('Bar Trigona', 34, 'Kuala Lumpur', 'Malaysia'),
('Analogue Initiative', 35, 'Singapore', 'Singapore'),
('Bar Trigona', 36, 'Kuala Lumpur', 'Malaysia'),
('Bee''s Knees', 37, 'Kyoto', 'Japan'),
('Mizunara: The Library', 38, 'Hong Kong', 'Hong Kong'),
('Barc', 39, 'Kathmandu', 'Nepal'),
('ZLB23', 40, 'Bengaluru', 'India'),
('Reka', 41, 'Kuala Lumpur', 'Malaysia'),
('Sidecar', 42, 'New Delhi', 'India'),
('CMYK', 43, 'Changsha', 'China'),
('The Public House', 44, 'Taipei', 'Taiwan'),
('Mahaniyom Cocktail Bar', 45, 'Bangkok', 'Thailand'),
('Alice', 46, 'Seoul', 'South Korea'),
('Quinary', 47, 'Hong Kong', 'Hong Kong'),
('Le Chamber', 48, 'Seoul', 'South Korea'),
('Atlas', 49, 'Singapore', 'Singapore'),
('Pine & Co', 50, 'Seoul', 'South Korea'),
('Obsidian Bar', 51, 'Shenzhen', 'China'),
('Pine & Co', 52, 'Seoul', 'South Korea'),
('Side Door', 53, 'Singapore', 'Singapore'),
('Soko', 54, 'Seoul', 'South Korea'),
('Bar Outrigger', 55, 'Goa', 'India'),
('Sago House', 56, 'Singapore', 'Singapore'),
('Lab', 57, 'Taipei', 'Taiwan'),
('Craftroom', 58, 'Osaka', 'Japan'),
('The Han-Jia', 59, 'Tainan', 'Taiwan'),
('Origin Bar', 60, 'Singapore', 'Singapore'),
('Stir', 61, 'Ho Chi Minh City', 'Vietnam'),
('Sidecar', 62, 'New Delhi', 'India'),
('Gong Gan', 63, 'Seoul', 'South Korea'),
('Backdoor Bodega', 64, 'Penang', 'Malaysia'),
('Sora', 65, 'Phnom Penh', 'Cambodia'),
('Wu (Nothingness)', 66, 'Taipei', 'Taiwan'),
('Gold Bar', 67, 'Tokyo', 'Japan'),
('Pantja', 68, 'Jakarta', 'Indonesia'),
('The Bombay Canteen', 69, 'Mumbai', 'India'),
('Tokyo Confidential', 70, 'Tokyo', 'Japan'),
('Mahaniyom Cocktail Bar', 71, 'Bangkok', 'Thailand'),
('Bar Mood', 72, 'Taipei', 'Taiwan'),
('Under Lab', 73, 'Taipei', 'Taiwan'),
('Epic', 74, 'Shanghai', 'China'),
('Maltail', 75, 'Kaohsiung', 'Taiwan'),
('Bee''s Knees', 76, 'Kyoto', 'Japan'),
('Night Hawk', 77, 'Singapore', 'Singapore'),
('The Curator', 78, 'Manila', 'Philippines'),
('The Bellwood', 79, 'Tokyo', 'Japan'),
('The Opposites', 80, 'Hong Kong', 'Hong Kong'),
('Sober Company', 81, 'Shanghai', 'China'),
('Firefly', 82, 'Bangkok', 'Thailand'),
('Workshop14', 83, 'Hanoi', 'Vietnam'),
('Raa', 84, 'Hiriketiya', 'Sri Lanka'),
('Coa', 85, 'Shanghai', 'China'),
('The Hudson Rooms', 86, 'Hanoi', 'Vietnam'),
('The Haflington', 87, 'Hanoi', 'Vietnam'),
('Mostly Harmless', 88, 'Hong Kong', 'Hong Kong'),
('Employees Only', 89, 'Singapore', 'Singapore'),
('Messenger Service', 90, 'Bangkok', 'Thailand'),
('Quinary', 91, 'Hong Kong', 'Hong Kong'),
('Coley', 92, 'Kuala Lumpur', 'Malaysia'),
('The Enigma Mansion', 93, 'Ho Chi Minh City', 'Vietnam'),
('Hideaway', 94, 'Goa', 'India'),
('Fura', 95, 'Singapore', 'Singapore'),
('Charles H', 96, 'Seoul', 'South Korea'),
('Pony Up', 97, 'Shanghai', 'China'),
('The Golden Tooth', 98, 'Jakarta', 'Indonesia'),
('The SG Club', 99, 'Tokyo', 'Japan'),
('Bar Nayuta', 100, 'Osaka', 'Japan');