/*
  # Insert Events Data

  1. Data Import
    - Insert all events from the provided data
    - Convert dates to proper format
    - Clean up descriptions and feature bars
*/

INSERT INTO events (name, date, time, venue, hotel, location, image_url, description, feature_bar, info_link) VALUES
('Keegan McGregor''s World Class Takeover', '2025-07-11', '20:00', 'SW Steakhouse', 'Wynn Palace', 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/bbaf12cb-659f-43e7-628e-4b74a2a29e00/Asia', 'Say hello to the reigning Diageo World Class Global Bartender of the Year 2024! Keegan McGregor brings his championship-winning cocktail menu straight from Canada to Wynn Palace, July 11-12 from 8pm onwards. Don''t miss the opportunity to try the award-winning cocktails that had everyone talking this past year - crafted by the master himself!', 'Keegan McGregor', 'https://www.instagram.com/p/DLPaTDsPsN_/'),

('Elliot Faber Takes Over Mizumi', '2025-07-11', '19:00', 'Mizumi', 'Wynn Palace', 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/7c17c60a-f39d-42af-b4e6-f278a32c8b00/Asia', 'The Canadian Sake Samurai has landed in Macau! Elliot Faber goes behind the bar at Wynn Palace''s Michelin-starred Mizumi on July 11 from 7pm onwards, serving sake-centered cocktails that perfectly complement their award-winning modern Japanese cuisine. Join him for an extraordinary meal or festive liquid dinner!', 'Elliot Faber', 'https://www.instagram.com/p/DLXDWhpPP4p/'),

('Nepal''s Finest: Barc x Tell Camellia x Courtroom', '2025-07-11', '20:00', 'Wing Lei Bar', 'Wynn Palace', 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/e39cb6ec-3835-4be0-382b-dec4e5bfd400/Asia', 'Nepal''s finest bar talents take over Wing Lei Bar for the first "clink" of Asia''s 50 Best Bars week! Meet Abhishek from Kathmandu''s Barc (No.39, Michter''s Art of Hospitality Award winner), Gagan from Hong Kong''s Tell Camellia (No.23), and Saan from Courtroom HK. Join them July 11 from 8pm and kick off the "Best" festivities with the best!', 'Barc, Tell Camellia, Courtroom', 'https://www.instagram.com/p/DLHmFObx1MT/'),

('SW Steakhouse x Born & Bred', '2025-07-11', '19:00', 'SW Steakhouse', 'Wynn Palace', 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/c7121a86-f95b-4a88-df42-a2f5a3d5fb00/Asia', 'Premium beef meets premium cocktails! This collaboration between SW Steakhouse and Born & Bred demonstrates how exceptional drinks enhance fine steakhouse dining. Carefully curated cocktail pairings designed specifically for premium beef selections showcase the perfect marriage of expert mixology with culinary excellence.', 'Born & Bred, Chef Kyung-hwan Min, Chef Helder Sequeira Amaral', 'https://www.instagram.com/p/DLhiK0NTL9H/'),

('Tea-Tales: Lakeview Palace x Yong Fu x Tell Camellia', '2025-07-11', '19:00', 'Lakeview Palace', 'Wynn Palace', 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/bbd221c3-9581-4dbe-b2e4-da33be7f6100/Asia', 'The tea cocktail journey continues! This extended collaboration between Lakeview Palace, Yong Fu, and Tell Camellia explores even more innovative applications of tea in mixology. Dive deeper into tea cocktail culture with additional presentations that demonstrate multiple approaches to incorporating traditional tea elements into contemporary drinking.', 'Tell Camellia, Yong Fu, Gagan Gurung, Chef Liu Zhen, Chef Kevin Zhu', 'https://www.instagram.com/p/DLkG4auTnSH/'),

('Chef Tam''s Seasons x Bar Mood', '2025-07-12', '18:00', 'Chef Tam''s Seasons', 'Wynn Palace', 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/5ca96e34-1cae-4c13-3524-850d8f52c500/Asia', 'Chef Tam, the icon behind this year''s Highest Climber restaurant, pairs his world-renowned Cantonese flavors with Nick Wu from Bar Mood Taipei. Get ready for the perfect gastronomy-mixology crossover featuring sustainability-focused cocktails on July 12 from 6pm.', 'Bar Mood, Nick Wu, Chef Tam Kwok Fung', 'https://www.instagram.com/p/DLhWbq8vjsF/'),

('50 Best Signature Session: Maybe Sammy x Drunken Fish', '2025-07-12', '19:00', 'Drunken Fish', 'Wynn Macau', 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/e0052ab8-33fa-479b-bc69-cb3e1e1c9600/Asia', 'For one night only, Maybe Sammy meets Drunken Fish in a first-ever dining and drinks collaboration at Wynn Macau. Hunter Gregory and Paolo Maffietti serve signature sips perfectly matched to Executive Chef Henry Zhang''s seafood-led menu. See you in Macau!', 'Maybe Sammy, Hunter Gregory, Paolo Maffietti, Chef Henry Zhang', 'https://www.instagram.com/p/DLmkKH_TYkg/'),

('Inventors'' Laboratory: Julio Bermejo x Sam Ross', '2025-07-12', '21:00', 'Wing Lei Bar', 'Wynn Palace', 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/e80acd5b-ec13-413e-c728-1a9fd34e5100/Asia', 'Two prominent cocktail inventors unite for the first time ever! Julio Bermejo, creator of Tommy''s Margarita, joins forces with Sam Ross from Attaboy, inventor of the Penicillin and Paper Plane. Try their signatures straight from the creators'' hands at Wing Lei Bar July 12, 9pm till late. Don''t miss this once-in-a-lifetime opportunity!', 'Julio Bermejo, Sam Ross', 'https://www.instagram.com/p/DLXMBNjRtmN/'),

('Teresa Cocktail Bar x ZLB23', '2025-07-12', '22:00', 'Palace Reserve Club', 'Wynn Palace', 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/40859ccd-0e74-483c-a042-a8038edb3800/Asia', 'Two award-winning bars from opposite ends of the Asia Pacific region showcase their distinct styles at Palace Reserve Club on July 12 from 10pm. Andrea Marseglia from New Zealand''s Teresa Cocktail Bar (Tales Best New International Cocktail Bar 2020) highlights seasonal local produce, while Rajib Mukherjee from India''s ZLB23 (No.40 Asia''s 50 Best Bars 2024) presents Kyoto-inspired prohibition-era cocktails.', 'Teresa Cocktail Bar, ZLB23', 'https://www.instagram.com/p/DLpR5l5ROJj'),

('Boilermaker at Bourke''s', '2025-07-12', '17:00', 'Bourke''s', NULL, 'Hong Kong', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/55e459ba-b113-46ba-22b5-01be3f921d00/Asia', 'The hottest new spot in Goa has landed! Five-star dive bar Boilermaker brings unmissable innovative yet unintimidated cocktails, including their signature Siolim Salsa - an ode to Goa with Altos tequila, jalapeño, gochujang & citrus. Big energy and strong pours from India''s own paradise, for just one night. It''s a chilled paradise for serious drinkers!', 'Boilermaker', 'https://www.instagram.com/p/DLjP9XpRWps/'),

('Bar Sathorn Takes Over OZONE', '2025-07-12', '19:00', 'OZONE', 'Ritz Carlton', 'Hong Kong', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/38c035c1-c449-4ad4-cc08-cd0cf59cd100/Asia', 'For one night only, Marco Dongi from Bangkok''s Bar Sathorn (50 Best Discovery list) takes over OZONE - the world''s highest rooftop bar! Let innovative cocktails add a new dimension to your evening July 12 at 7pm, promising a delightful journey through time blending tradition, culture, and innovation in every sip.', 'Bar Sathorn', 'https://www.instagram.com/p/DLZm4GkMA9p/'),

('The Aubrey''s "Unofficial Asia''s 50 Best Opening Party"', '2025-07-12', '22:30', 'The Aubrey', 'Mandarin Oriental', 'Hong Kong', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/c8a34d2d-4b17-4fcf-7dd1-015da8fa2000/Asia', 'The Aubrey hosts an "unofficial" opening party featuring acclaimed global bartenders. Experience signature cocktails from Happy Accidents (US), PS40 (Sydney), Artesian (London), and Manhattan (Singapore). Mark your calendars and arrive early for the liveliest night to kick off the festivities!', 'Happy Accidents, PS40, Artesian, Manhattan Bar, Stefano Bussi', 'https://www.instagram.com/p/DLZHPp-RgPl/?hl=en'),

('50 Best Signature Session: Sushi Mizumi x Martiny''s', '2025-07-13', '12:00', 'Sushi Mizumi', 'Wynn Palace', 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/45446cba-974b-44c9-56b5-80ccb0e76300/Asia', 'An exclusive collaboration where premium sushi artistry meets creative mixology innovation. Sushi Mizumi''s traditional Japanese techniques pair beautifully with Martiny''s contemporary cocktail craftsmanship, creating perfect harmony between two distinct culinary arts. This special session showcases how expert cocktails can elevate traditional sushi dining to extraordinary new heights.', 'Martiny''s, Takuma Watanabe, Chef Hironori Maeda', 'https://www.instagram.com/p/DK-ebAcAy4x/?img_index=3'),

('Hong Kong Takeover', '2025-07-13', '15:00', 'Wing Lei Bar', 'Wynn Palace', 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/a4a35213-a960-46c1-969d-63c5e4c98a00/Asia', 'Get ready for the warmest welcome on July 13! Hong Kong Takeover brings Mostly Harmless Bar, Artifact Bar, Call Me Al and We Are The Pontiac to Wing Lei Bar. These teams known for delicious concoctions and community-focused hospitality await you with open arms! 3pm-6pm: Ezra Star, J Frank and Mison. 6pm-9pm: Chloe & Ellie with Jen Queen and Nicole keep the energy going!', 'Mostly Harmless, The Pontiac, Artifact, Call Me Al', 'https://www.instagram.com/p/DLhVLs2xxHR/'),

('Palace Reserve Club Beach Club: Honky Tonks Tavern x Potato Head Beach Club', '2025-07-13', '15:00', 'Palace Reserve Club', 'Wynn Palace', 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/c696ff55-228a-4352-c95d-fe65b5bae500/Asia', 'Beach vibes meet premium cocktails! This tropical collaboration brings together two distinctive establishments at Palace Reserve Club, creating a vacation-like atmosphere with expertly crafted beach-inspired drinks. Dive into this unique partnership that combines the best of both worlds - relaxed beach club culture with sophisticated cocktail artistry.', 'Honky Tonks Tavern, Potato Head Beach Club Bali', 'https://www.instagram.com/p/DLR6YaoRVUJ/'),

('Asia''s 50 Best Bars Awards Ceremony', '2025-07-15', '20:00', 'TBA', NULL, 'Macau', 'https://imagedelivery.net/y2gc2AQWv5Cg-1Y3N7mCcg/5fb13aad-5c30-4bd9-4694-ce8cc697bd00/Asia', 'The moment we''ve all been waiting for! Join industry leaders, bartenders, and enthusiasts for the prestigious annual ceremony celebrating Asia''s finest bars. Feel the excitement as the rankings are revealed, honoring the innovation, hospitality, and craftsmanship that defines Asia''s dynamic cocktail scene. It''s the night that counts!', '', 'https://www.theworlds50best.com/bars/asia/');